//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="CitiesPortSoap11", Namespace="http://cities.sources.com")]
public partial class CitiesPortService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getCityOperationCompleted;
    
    private System.Threading.SendOrPostCallback getCitiesOperationCompleted;
    
    /// <remarks/>
    public CitiesPortService() {
        this.Url = "http://localhost:8080/ws/cities";
    }
    
    /// <remarks/>
    public event getCityCompletedEventHandler getCityCompleted;
    
    /// <remarks/>
    public event getCitiesCompletedEventHandler getCitiesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("getCityResponse", Namespace="http://cities.sources.com")]
    public getCityResponse getCity([System.Xml.Serialization.XmlElementAttribute(Namespace="http://cities.sources.com")] getCityRequest getCityRequest) {
        object[] results = this.Invoke("getCity", new object[] {
                    getCityRequest});
        return ((getCityResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCity(getCityRequest getCityRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCity", new object[] {
                    getCityRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public getCityResponse EndgetCity(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((getCityResponse)(results[0]));
    }
    
    /// <remarks/>
    public void getCityAsync(getCityRequest getCityRequest) {
        this.getCityAsync(getCityRequest, null);
    }
    
    /// <remarks/>
    public void getCityAsync(getCityRequest getCityRequest, object userState) {
        if ((this.getCityOperationCompleted == null)) {
            this.getCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCityOperationCompleted);
        }
        this.InvokeAsync("getCity", new object[] {
                    getCityRequest}, this.getCityOperationCompleted, userState);
    }
    
    private void OngetCityOperationCompleted(object arg) {
        if ((this.getCityCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCityCompleted(this, new getCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("getCitiesResponse", Namespace="http://cities.sources.com")]
    public getCitiesResponse getCities([System.Xml.Serialization.XmlElementAttribute(Namespace="http://cities.sources.com")] getCitiesRequest getCitiesRequest) {
        object[] results = this.Invoke("getCities", new object[] {
                    getCitiesRequest});
        return ((getCitiesResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCities(getCitiesRequest getCitiesRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCities", new object[] {
                    getCitiesRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public getCitiesResponse EndgetCities(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((getCitiesResponse)(results[0]));
    }
    
    /// <remarks/>
    public void getCitiesAsync(getCitiesRequest getCitiesRequest) {
        this.getCitiesAsync(getCitiesRequest, null);
    }
    
    /// <remarks/>
    public void getCitiesAsync(getCitiesRequest getCitiesRequest, object userState) {
        if ((this.getCitiesOperationCompleted == null)) {
            this.getCitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCitiesOperationCompleted);
        }
        this.InvokeAsync("getCities", new object[] {
                    getCitiesRequest}, this.getCitiesOperationCompleted, userState);
    }
    
    private void OngetCitiesOperationCompleted(object arg) {
        if ((this.getCitiesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCitiesCompleted(this, new getCitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cities.sources.com")]
public partial class getCityRequest {
    
    private uint idField;
    
    /// <remarks/>
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cities.sources.com")]
public partial class city {
    
    private string nameField;
    
    private uint idField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cities.sources.com")]
public partial class getCityResponse {
    
    private city cityField;
    
    /// <remarks/>
    public city city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cities.sources.com")]
public partial class getCitiesRequest {
    
    private string termField;
    
    /// <remarks/>
    public string term {
        get {
            return this.termField;
        }
        set {
            this.termField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cities.sources.com")]
public partial class getCitiesResponse {
    
    private city[] citiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public city[] cities {
        get {
            return this.citiesField;
        }
        set {
            this.citiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getCityCompletedEventHandler(object sender, getCityCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public getCityResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((getCityResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getCitiesCompletedEventHandler(object sender, getCitiesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public getCitiesResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((getCitiesResponse)(this.results[0]));
        }
    }
}
