//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.14 at 01:05:48 PM PDT 
//


package com.sources.hotels;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sources.hotels package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sources.hotels
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetHotelsResponse }
     * 
     */
    public GetHotelsResponse createGetHotelsResponse() {
        return new GetHotelsResponse();
    }

    /**
     * Create an instance of {@link Hotels }
     * 
     */
    public Hotels createHotels() {
        return new Hotels();
    }

    /**
     * Create an instance of {@link GetHotelResponse }
     * 
     */
    public GetHotelResponse createGetHotelResponse() {
        return new GetHotelResponse();
    }

    /**
     * Create an instance of {@link Hotel1 }
     * 
     */
    public Hotel1 createHotel1() {
        return new Hotel1();
    }

    /**
     * Create an instance of {@link GetHotelsRequest }
     * 
     */
    public GetHotelsRequest createGetHotelsRequest() {
        return new GetHotelsRequest();
    }

    /**
     * Create an instance of {@link GetHotelRequest }
     * 
     */
    public GetHotelRequest createGetHotelRequest() {
        return new GetHotelRequest();
    }

    /**
     * Create an instance of {@link GetHotelDetailsRequest }
     * 
     */
    public GetHotelDetailsRequest createGetHotelDetailsRequest() {
        return new GetHotelDetailsRequest();
    }

    /**
     * Create an instance of {@link GetHotelDetailsResponse }
     * 
     */
    public GetHotelDetailsResponse createGetHotelDetailsResponse() {
        return new GetHotelDetailsResponse();
    }

    /**
     * Create an instance of {@link Hotel }
     * 
     */
    public Hotel createHotel() {
        return new Hotel();
    }

    /**
     * Create an instance of {@link PriceList }
     * 
     */
    public PriceList createPriceList() {
        return new PriceList();
    }

    /**
     * Create an instance of {@link Facilities }
     * 
     */
    public Facilities createFacilities() {
        return new Facilities();
    }

    /**
     * Create an instance of {@link Contacts }
     * 
     */
    public Contacts createContacts() {
        return new Contacts();
    }

}
