//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.10 at 02:41:04 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://hotels.sources.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sources.hotels;
