//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 02:46:39 AM PDT 
//


package com.sources.hotels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for price_list complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="price_list">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="single_room" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="double_room" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="triple_room" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *       &lt;/sequence>
 *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" default="EUR" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "price_list", propOrder = {
    "singleRoom",
    "doubleRoom",
    "tripleRoom"
})
public class PriceList {

    @XmlElement(name = "single_room")
    @XmlSchemaType(name = "unsignedInt")
    protected long singleRoom;
    @XmlElement(name = "double_room")
    @XmlSchemaType(name = "unsignedInt")
    protected long doubleRoom;
    @XmlElement(name = "triple_room")
    @XmlSchemaType(name = "unsignedInt")
    protected long tripleRoom;
    @XmlAttribute(name = "currency")
    protected String currency;

    /**
     * Gets the value of the singleRoom property.
     * 
     */
    public long getSingleRoom() {
        return singleRoom;
    }

    /**
     * Sets the value of the singleRoom property.
     * 
     */
    public void setSingleRoom(long value) {
        this.singleRoom = value;
    }

    /**
     * Gets the value of the doubleRoom property.
     * 
     */
    public long getDoubleRoom() {
        return doubleRoom;
    }

    /**
     * Sets the value of the doubleRoom property.
     * 
     */
    public void setDoubleRoom(long value) {
        this.doubleRoom = value;
    }

    /**
     * Gets the value of the tripleRoom property.
     * 
     */
    public long getTripleRoom() {
        return tripleRoom;
    }

    /**
     * Sets the value of the tripleRoom property.
     * 
     */
    public void setTripleRoom(long value) {
        this.tripleRoom = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        if (currency == null) {
            return "EUR";
        } else {
            return currency;
        }
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

}
